import type { Metadata } from "next";
import { Outfit, Roboto_Mono } from 'next/font/google'
import { ThemeProvider } from 'next-themes'
import "./globals.css";

const outfit = Outfit({
  variable: '--font-outfit',
  subsets: ["latin"],
});

const robotoMono = Roboto_Mono({
  variable: '--font-roboto-mono',
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en"
      suppressHydrationWarning>
      <body
        className={`${outfit.variable} ${robotoMono.variable} font-sans antialiased h-screen`}
      >
        <ThemeProvider attribute="class">
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
